server:
  port: 8080
spring:
  application:
    name: "personas"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: jdbc:postgresql://banco_db:5432/BaseDatos?currentSchema=public
    username: banco
    password: banco
    driverClassName: org.postgresql.Driver
    logging:
      level:
        org.springframework.web: DEBUGrec
  jpa:
    #properties:
    #hibernate:
    #dialect: "com.test.CustomPostgreSQLDialect"
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
db:
  manangment:
    url: jdbc:postgresql://banco_db:5432/public
    host: banco_db
    bdname: BaseDatos
    port: 5432
    username: banco
    password: banco
rabbit:
  host: rabbitmq
  port: 5672
  secret:
    region: guest
    name: guest
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
